api/urls.py
from django.urls import path

from api import views

urlpatterns = [
    path('v1/add_favorite/', views.add_favorite, name='add_favorite'),
    path('v1/remove_favorite/<int:recipe_id>/',
         views.remove_favorite, name='remove_favorite'),
    path('v1/add_wishlist/', views.add_wishlist, name='add_wishlist'),
    path('v1/remove_wishlist/<int:recipe_id>/',
         views.remove_wishlist, name='remove_wishlist'),
    path('v1/add_subscription/', views.add_subscription, name='add_subscription'),
    path('v1/remove_subscription/<int:following_id>/',
         views.remove_subscription, name='remove_subscription'),
    path('v1/<str:username>/<int:recipe_id>/remove/',
         views.remove_recipe, name='remove_recipe'),
    path('v1/ingredients/', views.get_ingredients, name='get_ingredients'),
    path('v1/print_cart/', views.get_cart, name='get_cart'),
]

foodgram_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('auth/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls')),
    path('', include('recipes.urls'))
]


handler404 = 'recipes.views.page_not_found' # noqa
handler500 = 'recipes.views.server_error' # noqa


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.shortcuts import get_object_or_404
from multiselectfield import MultiSelectField
from pytils.translit import slugify

User = get_user_model()

TAGS_CHOICES = (
    ('breakfast', 'Завтрак'),
    ('lunch', 'Обед'),
    ('dinner', 'Ужин')
)


class Ingredient(models.Model):
    title = models.CharField('Ингредиент', max_length=250, unique=True)
    dimension = models.CharField(
        max_length=25,
        verbose_name='Единица измерения'
    )

    class Meta:
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'
        ordering = ['title', ]

    def __str__(self):
        return f'{self.title} / {self.dimension}'


class Recipe(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='recipes',
        verbose_name='Автор'
    )
    title = models.CharField(
        'Название рецепта',
        max_length=150,
        unique=True
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    description = models.TextField(
        blank=True,
        default='',
        verbose_name='Описание'
    )
    image = models.ImageField(
        upload_to='recipes/',
        verbose_name='Изображение'
    )
    ingredients = models.ManyToManyField(
        Ingredient,
        verbose_name='Игредиенты',
        through='RecipeIngredients'
    )
    tags = MultiSelectField(
        choices=TAGS_CHOICES,
        verbose_name='Теги'
    )
    cooking_time = models.PositiveSmallIntegerField(
        'Время приготовления,мин',
        default=0
    )

    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ['title', ]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Recipe, self).save(*args, **kwargs)


class RecipeIngredients(models.Model):
    amount = models.PositiveIntegerField(verbose_name='Количество')
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        verbose_name='Рецепт'
    )
    ingredient = models.ForeignKey(
        Ingredient,
        on_delete=models.CASCADE,
        verbose_name='Ингредиент'
    )

    @staticmethod
    def add_ingredient(recipe_id, title, amount):
        ingredient = get_object_or_404(Ingredient, title=title)
        recipe = get_object_or_404(Recipe, id=recipe_id)
        return RecipeIngredients.objects.get_or_create(
            recipe=recipe,
            ingredient=ingredient,
            amount=amount
        )


class Follow(models.Model):
    subscriber = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='subscriber',
        verbose_name='Подписчик',
        help_text='Автор подписки'
    )
    following = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Подписан на',
        help_text='Объект подписки'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'


class Favorite(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        related_name='favorite_subscriber',
        help_text='автор избранного'
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='favorite_recipe',
        verbose_name='Подписан на',
        help_text='Рецепты в избранном'
    )

    class Meta:
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранное'


class Cart(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='subscriber_cart'
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='recipe_cart'
    )

foodgram_project/templates/authForm.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Войти на сайт</title>
    <link rel="stylesheet" href="./pages/form.css">
</head>
<body class="body">
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            <ul class="nav__items list">
                <li class="nav__item nav__item_disabled"><a href="#" class="nav__link link">Рецепты</a></li>
                <li class="nav__item nav__item_disabled"><a href="#" class="nav__link link">Список покупок</a></li>
            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
                <li class="nav__item"><a href="#" class="button button_style_blue">Создать аккаунт</a></li>
            </ul>
        </div>
    </nav>
</header>
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Войти на сайт</h1>
    </div>
    <div class="form-container">
        <form class="form">
            <div class="form__group">
                <label for="id_username" class="form__label">Имя</label>
                <div class="form__field-group">
                    <input type="text" name="username" id="id_username" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_password" class="form__label">Пароль</label>
                <div class="form__field-group">
                    <input type="password" name="password" id="id_password" class="form__input">
                    <span class="form__error">Имя пользователя и пароль не совпадают. Введите правильные данные.</span>
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Войти</button>
                <a class="form__forgot-link">Забыли пароль?</a>
            </div>
        </form>
    </div>


</main>
<footer class="footer">
    <div class="footer__container container">
        <a href="#" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="#" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="#" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>
</body>
</html>

foodgram_project/templates/indexAuth.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Рецепты</title>
    <link rel="stylesheet" href="/static/pages/index.css">
</head>
<body class="body">
  <header class="header">
      <nav class="nav">
          <div class="nav__container container">
              <ul class="nav__items list">
                  <li class="nav__item nav__item_active"><a href="{% url 'home' %}" class="nav__link link">Рецепты</a></li>
                  <li class="nav__item"><a href="#" class="nav__link link">Мои подписки</a></li>
                  <li class="nav__item"><a href="{% url 'recipe_new' %}" class="nav__link link">Создать рецепт</a></li>
                  <li class="nav__item"><a href="#" class="nav__link link">Избранное</a></li>
                  <li class="nav__item"><a href="#" class="nav__link link">Список покупок</a> <span class="badge badge_style_blue nav__badge" id="counter">4</span></li>

              </ul>
              <ul class="nav__items list">
                  <li class="nav__item"><a href="#" class="nav__link link">Изменить пароль</a></li>
                  <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
              </ul>
          </div>
      </nav>
  </header>
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Рецепты</h1>
            <ul class="tags">
                <li class="tags__item">
                    <a id="breakfast" class="tags__checkbox tags__checkbox_style_orange tags__checkbox_active" href="#"></a>
                    <span class="tags__label">Завтрак</span>
                </li>
                <li class="tags__item">
                    <a id="lunch" class="tags__checkbox tags__checkbox_style_green tags__checkbox_active" href="#"></a>
                    <span for="lunch" class="tags__label">Обед</span>
                </li>
                <li class="tags__item">
                    <a id="dinner" class="tags__checkbox tags__checkbox_style_purple tags__checkbox_active" href="#"></a>
                    <label for="dinner" class="tags__label">Ужин</label>
                </li>
            </ul>
        </div>
        <div class="card-list">
            {% for recipe in recipes %}
                <div class="card" data-id="120">
                    <a href="{{ recipe.get_absolute_url }}" class="link" target="_blank"><img src="{{ recipe.image.url }}" alt="Какой-то текст" class="card__image"></a>
                    <div class="card__body">
                        <a class="card__title link" href="{{ recipe.get_absolute_url }}" target="_blank">{{ recipe.title }}</a>
                        <ul class="card__items">
                            <li class="card__item"><span class="badge badge_style_green">Обед</span></li>
                            <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>
                            <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>
                        </ul>
                        <div class="card__items card__items_column">
                            <p class="card__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
                            <p class="card__text"><span class="icon-user"></span> <a href="#" style="color: black">{{ recipe.author.get_full_name }}</a></p>
                        </div>
                    </div>
                    <div class="card__footer">
                        <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
                        <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
                    </div>
                </div>
<!--        <div class="card" data-id="121">-->
<!--            <a href="#" class="link" target="_blank"><img src="./images/testCardImg.png" alt="Какой-то текст" class="card__image"></a>-->
<!--            <div class="card__body">-->
<!--                <a class="card__title link" href="#" target="_blank">Французские тосты</a>-->
<!--                <ul class="card__items">-->
<!--                    <li class="card__item"><span class="badge badge_style_green">Обед</span></li>-->
<!--                    <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>-->
<!--                    <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>-->
<!--                </ul>-->
<!--                <div class="card__items card__items_column">-->
<!--                    <p class="card__text"><span class="icon-time"></span> 20 мин.</p>-->
<!--                    <p class="card__text"><span class="icon-user"></span> <a href="#" style="color: black">Вероника Чернова</a></p>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="card__footer">-->
<!--                <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>-->
<!--                <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="card" data-id="122">-->
<!--            <a href="#" class="link" target="_blank"><img src="./images/testCardImg.png" alt="Какой-то текст" class="card__image"></a>-->
<!--            <div class="card__body">-->
<!--                <a class="card__title link" href="#" target="_blank">Французские тосты</a>-->
<!--                <ul class="card__items">-->
<!--                    <li class="card__item"><span class="badge badge_style_green">Обед</span></li>-->
<!--                    <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>-->
<!--                    <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>-->
<!--                </ul>-->
<!--                <div class="card__items card__items_column">-->
<!--                    <p class="card__text"><span class="icon-time"></span> 20 мин.</p>-->
<!--                    <p class="card__text"><span class="icon-user"></span> <a href="#" style="color: black">Вероника Чернова</a></p>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="card__footer">-->
<!--                <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>-->
<!--                <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="card" data-id="123">-->
<!--            <a href="#" class="link" target="_blank"><img src="./images/testCardImg.png" alt="Какой-то текст" class="card__image"></a>-->
<!--            <div class="card__body">-->
<!--                <a class="card__title link" href="#" target="_blank">Французские тосты</a>-->
<!--                <ul class="card__items">-->
<!--                    <li class="card__item"><span class="badge badge_style_green">Обед</span></li>-->
<!--                    <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>-->
<!--                    <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>-->
<!--                </ul>-->
<!--                <div class="card__items card__items_column">-->
<!--                    <p class="card__text"><span class="icon-time"></span> 20 мин.</p>-->
<!--                    <p class="card__text"><span class="icon-user"></span> <a href="#" style="color: black">Вероника Чернова</a></p>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="card__footer">-->
<!--                <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>-->
<!--                <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="card" data-id="124">-->
<!--            <a href="#" class="link" target="_blank"><img src="./images/testCardImg.png" alt="Какой-то текст" class="card__image"></a>-->
<!--            <div class="card__body">-->
<!--                <a class="card__title link" href="#" target="_blank">Французские тосты</a>-->
<!--                <ul class="card__items">-->
<!--                    <li class="card__item"><span class="badge badge_style_green">Обед</span></li>-->
<!--                    <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>-->
<!--                    <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>-->
<!--                </ul>-->
<!--                <div class="card__items card__items_column">-->
<!--                    <p class="card__text"><span class="icon-time"></span> 20 мин.</p>-->
<!--                    <p class="card__text"><span class="icon-user"></span> <a href="#" style="color: black">Вероника Чернова</a></p>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="card__footer">-->
<!--                <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>-->
<!--                <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>-->
<!--            </div>-->
<!--        </div>-->
        {% endfor %}
    </div>
        <nav class="pagination" aria-label="Search results pages">
            <ul class="pagination__container">
                <li class="pagination__item"><a class="pagination__link link" href="#"><span class="icon-left"></span></a></li>
                <li class="pagination__item pagination__item_active"><a class="pagination__link link" href="#">1</a></li>
                <li class="pagination__item"><a class="pagination__link link" href="#">2</a></li>
                <li class="pagination__item"><a class="pagination__link link" href="#">3</a></li>
                <li class="pagination__item"><a class="pagination__link link" href="#">4</a></li>
                <li class="pagination__item"><a class="pagination__link link" href="#">5</a></li>
                <li class="pagination__item"><a class="pagination__link link" href="#"><span class="icon-right"></span></a></li>
            </ul>
        </nav>
    </main>
    <footer class="footer">
        <div class="footer__container container">
            <a href="#" class="footer__brand link">Продуктовый помощник</a>
            <ul class="footer__items">
                <li class="footer__item"><a href="#" class="footer__link link">Об авторе </a></li>
                <li class="footer__item"><a href="#" class="footer__link link">Технологии</a></li>
            </ul>
        </div>
    </footer>
  <script src="./js/components/MainCards.js"></script>

  <script src="/static/js/components/Purchases.js"></script>
  <script src="/static/js/components/Favorites.js"></script>

  <script src="/static/js/config/config.js"></script>
  <script src="/static/js/components/CardList.js"></script>
  <script src="/static/js/components/Header.js"></script>

  <script src="/static/js/api/Api.js"></script>
  <script src="/static/indexAuth.js"></script>
</body>
</html>

foodgram_project/templates/reg.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Регистрация</title>
    <link rel="stylesheet" href="/static/pages/form.css">
</head>
<body class="body">
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            <ul class="nav__items list">
                <li class="nav__item nav__item_disabled"><a href="#" class="nav__link link">Рецепты</a></li>
                <li class="nav__item nav__item_disabled"><a href="#" class="nav__link link">Список покупок</a></li>
            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
                <li class="nav__item"><a href="#" class="button button_style_blue">Создать аккаунт</a></li>
            </ul>
        </div>
    </nav>
</header>
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Регистрация</h1>
    </div>
    <div class="form-container">
        <form class="form">
            <div class="form__group">
                <label for="id_first_name" class="form__label">Имя</label>
                <div class="form__field-group">
                    <input type="text" name="first_name" id="id_first_name" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_username" class="form__label">Имя пользователя</label>
                <div class="form__field-group">
                    <input type="text" name="username" id="id_username" class="form__input">
                    <span class="form__error">Имя пользователя и пароль не совпадают. Введите правильные данные.
                    </span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_email" class="form__label">Адрес электронной почты</label>
                <div class="form__field-group">
                    <input type="email" name="email" id="id_email" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_password" class="form__label">Пароль</label>
                <div class="form__field-group">
                    <input type="password" name="password" id="id_password" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Создать аккаунт</button>
            </div>
        </form>
    </div>


</main>
<footer class="footer">
    <div class="footer__container container">
        <a href="#" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="#" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="#" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>
</body>
</html>

foodgram_project/templates/singlePageNotAuth.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ recipe.title }}</title>
    <link rel="stylesheet" href="/static/pages/single.css">
</head>
<body class="body">
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            <ul class="nav__items list">
                <li class="nav__item nav__item_active"><a href="{% url 'home' %}" class="nav__link link">Рецепты</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Список покупок</a><span class="badge badge_style_blue nav__badge" id="counter">4</span></li>
            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
                <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
            </ul>
        </div>
    </nav>
</header>
    <main class="main container">
        <div class="single-card" data-id="371">
            <img src="{{ recipe.image.url }}" alt="какой-то текст" class="single-card__image">
            <div class="single-card__info">
                <div class="single-card__header-info">
                    <h1 class="single-card__title">{{ recipe.title }}</h1>

                </div>
                <ul class="single-card__items">
                    <li class="single-card__item"><span class="badge badge_style_green">Обед</span></li>
                    <li class="single-card__item"><span class="badge badge_style_orange">Завтрак</span></li>
                    <li class="single-card__item"><span class="badge badge_style_purple">Ужин</span></li>
                </ul>
                <div class="single-card__items single-card__items_column">
                    <p class="single-card__text"><span class="icon-time"></span>{{ recipe.cooking_time }} мин.</p>
                    <p class="single-card__text"><span class="icon-user"></span>{{ recipe.author.get_full_name }}</p>
                </div>
                <ul class="single-card__items">
                    <li class="single-card__item"><button class="button button_style_blue" name="purchases" data-out><span class="icon-plus"></span> Добавить в покупки</button></li>
                </ul>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Ингридиенты:</h3>
                    <div class="single-card__items single-card__items_column">
                        {% for ingredient in recipe.recipeingredients_set.all %}
                            <p class=" single-card__section-item">{{ ingredient.ingredient.title }} - {{ ingredient.quantity }} {{ ingredient.ingredient.unit }}.</p>
<!--                        <p class=" single-card__section-item">Молоко - 200 мл.</p>-->
<!--                        <p class=" single-card__section-item">Тосты - 4 шт.</p>-->
<!--                        <p class=" single-card__section-item">Сахар 2 сл.л.</p>-->
<!--                        <p class=" single-card__section-item">Яйцо - 2 шт.</p>-->
<!--                        <p class=" single-card__section-item">Молоко - 200 мл.</p>-->
                        {% endfor %}
                    </div>
                </div>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Описание:</h3>
                    <p class=" single-card__section-text">{{ recipe.description }}</p>
<!--                    <p class=" single-card__section-text">Полить сверху сиропом топинамбура и украсить ягодами.</p>-->
                </div>
            </div>
        </div>
    </main>
    <footer class="footer">
        <div class="footer__container container">
            <a href="#" class="footer__brand link">Продуктовый помощник</a>
            <ul class="footer__items">
                <li class="footer__item"><a href="#" class="footer__link link">Об авторе </a></li>
                <li class="footer__item"><a href="#" class="footer__link link">Технологии</a></li>
            </ul>
        </div>
    </footer>
<script src="/static/js/components/Purchases.js"></script>
<script src="/static/js/config/config.js"></script>
<script src="/static/js/components/MainCards.js"></script>
<script src="/static/js/components/SingleCard.js"></script>
<script src="/static/js/components/Header.js"></script>
<script src="/static/js/api/Api.js"></script>
<script src="/static/singlePageNotAuth.js"></script>
</body>
</html>