about/urls.py
from django.urls import path
from about import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('contacts/', views.AboutContactsView.as_view(), name='contacts'),
]

api/urls.py
from django.urls import path

from api import views

urlpatterns = [
    path('v1/add_favorite/', views.add_favorite, name='add_favorite'),
    path('v1/remove_favorite/<int:recipe_id>/',
         views.remove_favorite, name='remove_favorite'),
    path('v1/add_wishlist/', views.add_wishlist, name='add_wishlist'),
    path('v1/remove_wishlist/<int:recipe_id>/',
         views.remove_wishlist, name='remove_wishlist'),
    path('v1/add_subscription/', views.add_subscription, name='add_subscription'),
    path('v1/remove_subscription/<int:following_id>/',
         views.remove_subscription, name='remove_subscription'),
    path('v1/<str:username>/<int:recipe_id>/remove/',
         views.remove_recipe, name='remove_recipe'),
    path('v1/ingredients/', views.get_ingredients, name='get_ingredients'),
    path('v1/print_cart/', views.get_cart, name='get_cart'),
]

foodgram_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('auth/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls')),
    path('', include('recipes.urls'))
]


handler404 = 'recipes.views.page_not_found' # noqa
handler500 = 'recipes.views.server_error' # noqa


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Рецепты {% endblock %} | Продуктовый помощник</title>
    {% block style %}
    {% endblock %}
</head>
<body class="body">
    <header class="header">
        {% include 'nav.html' %}
    </header>
    <main class="main container">
        {% block content %}
        {% endblock %}
    </main>
    {% include 'footer.html' %}
    {% block script %}
    {% endblock %}
</body>
</html>

templates/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'index' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'about:author' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'about:tech' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

templates/index.html
{% extends "base.html" %}
{% block title %}Рецепты{% endblock %}

{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block content %}
<div class="main__header">
    <h1 class="main__title">Рецепты</h1>
    {% include 'tags.html' %}
</div>


<div class="card-list">
    {% for recipe in page %}
        {% include 'recipes/recipe.html' %}
    {% endfor %}
</div>


{% if page.has_other_pages %}
    {% include "paginator.html" with items=page paginator=paginator %}
{% endif %}

{% endblock %}

{% block script %}
<script src="{% static 'js/components/MainCards.js' %}"></script>

<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/Favorites.js' %}"></script>

<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

<script src="{% static 'js/api/Api.js' %}"></script>
{% if user.is_authenticated %}
    <script src="{% static 'indexAuth.js' %}"></script>
{% else %}
    <script src="{% static 'indexNotAuth.js' %}"></script>
{% endif %}
{% endblock %}

templates/nav.html
<nav class="nav">
    <div class="nav__container container">
        {% if request.user.is_authenticated %}
        <ul class="nav__items list">
            {% url 'index' as index %}
                <li class="nav__item {% if request.path  == index %}nav__item_active{% endif %}"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
            {% url 'feed' as feed %}
                <li class="nav__item {% if request.path  == feed %}nav__item_active{% endif %}"><a href="{% url 'feed' %}" class="nav__link link">Мои подписки</a></li>
            {% url 'new' as new %}
                <li class="nav__item {% if request.path  == new %}nav__item_active{% endif %}"><a href="{% url 'new' %}" class="nav__link link">Создать рецепт</a></li>
            {% url 'favorites' as favorites %}
                <li class="nav__item {% if request.path  == favorites %}nav__item_active{% endif %}"><a href="{% url 'favorites' %}" class="nav__link link">Избранное</a></li>
            {% url 'wishlist' as wishlist %}
            {% load wishlist_count %}
            <li class="nav__item {% if request.path  == wishlist %}nav__item_active{% endif %}">
                <a href="{% url 'cart' %}" class="nav__link link">Список покупок</a>
                <span class="badge badge_style_blue nav__badge" id="counter">{% if request.user|wishlist_count > 0 %}{{ request.user|wishlist_count }}{% endif %}</span>
            </li>
        </ul>
        <ul class="nav__items list">
            <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
            <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
        </ul>
        {% else %}
        <ul class="nav__items list">
            {% url 'index' as index %}
            <li class="nav__item {% if request.path  == index %}nav__item_active{% endif %}"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
        </ul>
        <ul class="nav__items list">
            <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
            <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
        </ul>
        {% endif %}
    </div>
</nav>

templates/paginator.html
{% load set_get_params %}
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        {% if items.has_previous %}
            <li class="pagination__item"><a class="pagination__link link"
                    href="?{% set_page request paginator.previous_page_number %}"><span class="icon-left"></span></a>
            </li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if items.number == i %}
                <li class="pagination__item pagination__item_active"><a class="pagination__link link"
                        href="?{% set_page request i %}">{{ i }}</a>
                </li>
            {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="?{% set_page request i %}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if items.has_next %}
            <li class="pagination__item"><a class="pagination__link link" href="?{% set_page request paginator.next_page_number %}">
                    <span class="icon-right"></span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>

templates/tags.html
<ul class="tags">
    {% load set_get_params %}
    <li class="tags__item">
        {% if "breakfast" in tags %}
            <a id="breakfast" class="tags__checkbox tags__checkbox_style_orange tags__checkbox_active" href="?{% set_tags request 'breakfast' %}"></a>
        {% else %}
            <a id="breakfast" class="tags__checkbox tags__checkbox_style_orange tags__checkbox" href="?{% set_tags request 'breakfast' %}"></a>
        {% endif %}
            <a class="card__title link" href="?{% set_tags request 'breakfast' %}"><span class="tags__label">Завтрак</span></a>
    </li>
    <li class="tags__item">
        {% if "lunch" in tags %}
            <a id="lunch" class="tags__checkbox tags__checkbox_style_green tags__checkbox_active" href="?{% set_tags request 'lunch' %}"></a>
        {% else %}
            <a id="lunch" class="tags__checkbox tags__checkbox_style_green tags__checkbox" href="?{% set_tags request 'lunch' %}"></a>
        {% endif %}
            <a class="card__title link" href="?{% set_tags request 'lunch' %}"><span for="lunch" class="tags__label">Обед</span></a>
    </li>
    <li class="tags__item">
        {% if "dinner" in tags %}
            <a id="dinner" class="tags__checkbox tags__checkbox_style_purple tags__checkbox_active" href="?{% set_tags request 'dinner' %}"></a>
        {% else %}
            <a id="dinner" class="tags__checkbox tags__checkbox_style_purple tags__checkbox" href="?{% set_tags request 'dinner' %}"></a>
        {% endif %}
            <a class="card__title link" href="?{% set_tags request 'dinner' %}"><span for="dinner" class="tags__label">Ужин</span></a>
    </li>
</ul>